config/routes.rb
Whopayforcoffe::Application.routes.draw do

  get 'queues/:queue' => 'counters#index', :as => :queues
  post 'queues/:queue/pay' => 'counters#pay', :as => :pay
  post 'queues/:queue/skip' => 'counters#skip', :as => :skip

end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController

  def index
# raise params.inspect
    @counters = Counter.find_all_by_queue params[:queue]

    @skipped = session[:skipped] || {}
    if @skipped.keys.count >= @counters.count
      @skipped = {}
      session[:skipped] = @skipped
    end

    min_count = 10000000000000000
    @counters.each do |c|
      unless @skipped.has_key? c.title
        if c.count < min_count 
          min_count = c.count
          @highlited_title = c.title
        end
      end
    end
  end

  def pay
#    raise params.inspect
    @counter = Counter.find_by_title_and_queue params[:highlited_title], params[:queue]
    if( @counter )
      @counter.count+=1
      @counter.save!
    end
    session[:skipped]={}
    redirect_to queues_path params[:queue]
  end

  def skip
#    raise params.inspect
    if session[:skipped] == nil
      session[:skipped] = {}
    end
    session[:skipped][params[:highlited_title]] = 0
    redirect_to queues_path params[:queue]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/counters/index.html.haml
%h1 Participants

%table#counters
  %thead
    %tr
      %th Person
      %th Count
      %th Updated
  %tbody
    - @counters.each do |c|
      %tr{:class => if( c.title == @highlited_title) then 'hilite' end}
        %td= c.title
        %td= c.count
        %td= c.updated_at.in_time_zone("Asia/Seoul")
%table
  %tr
    %td= button_to 'Pay', pay_path( params[:queue], :highlited_title => @highlited_title )
    %td= button_to 'Skip', skip_path( params[:queue], :highlited_title => @highlited_title )

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Who Pay Now?
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Who Pay Now?
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield